title: tui.sh
description: terminal user interface only bash without ncurses.
show_downloads: true
remote_theme: nikescar/jekyll-theme-rtd
plugins:
- jekyll-remote-theme

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

# Theme settings
repo_url: 'https://tui.dure.app'
edit_on_github: true
github_docs_folder: false
sticky_navigation: true
prev_next_buttons_location: both
search_enabled: false
site_author: Woojae, Park
# logo: 'https://tui.dure.app/assets/css/theme.css'
# site_favicon: 'https://tui.dure.app/assets/img/favicon.ico'
# theme: 'https://nikescar.github.io/jekyll-theme-rtd/assets/css/theme.css'
# extra_theme: 'https://nikescar.github.io/jekyll-theme-rtd/assets/css/theme_extra.css'
prev_next_buttons_location: None
prev_next_buttons_location: top
prev_next_buttons_location: bottom
prev_next_buttons_location: both
# google_analytics: UA-XXXXX-Y
google_analytics_anonymize_ip: true
# The highlight.js library provides 79 different colours for their syntax highlighting. The default is github-gist.
hljs_style: github-gist
exclude: ['tui_web_src/*','tui.ex.yaml','tui.sh.yaml']
