import { A } from "@solidjs/router";
import { createSignal } from "solid-js";
import { TextField } from "@kobalte/core/text-field";
import "./overview.css";
import LogViewer from "~/components/LogViewer";

// let div = document.getElementById("target");
//         div.onload = function() {
//             div.style.height =
//             div.contentWindow.document.body.scrollHeight + 'px';
//         }

function Status() {
  return (
    <>
      <h2>Crontab Status : </h2>
      <LogViewer readpath="/proc/crontab" boxlabel="-Autogenerated by bkit." />

      <h2>Service Status : </h2>
      <LogViewer
        readpath="/proc/bkitservices"
        boxlabel="-Autogenerated by bkit."
      />
    </>
  );
}

export default Status;
